import {get,list,put} from "@vercel/blob";
import fs from "node:fs/promises";
import os from "node:os";
import path from "node:path";
export type QueueItem={id:string;filename:string;title:string;status:"queued"|"published"|"failed";scheduledAt:string;blobPath:string;youtubeVideoId?:string;createdAt:string};
const prefix="news/queue/";
async function readJson(p:string){const token=process.env.BLOB_READ_WRITE_TOKEN;if(!token)return null;try{const r=await get(p,{access:"private",token});if(!r?.stream)return null;const rd=r.stream.getReader();const c:Buffer[]=[];while(true){const x=await rd.read();if(x.done)break;if(x.value)c.push(Buffer.from(x.value));}return JSON.parse(Buffer.concat(c).toString()) as QueueItem;}catch{return null;}}
export async function listQueue(){const token=process.env.BLOB_READ_WRITE_TOKEN;if(!token)return [];const {blobs}=await list({prefix,limit:1000,token});const out:QueueItem[]=[];for(const b of blobs.filter(x=>x.pathname.endsWith(".json"))){const x=await readJson(b.pathname);if(x)out.push(x);}return out.sort((a,b)=>a.scheduledAt.localeCompare(b.scheduledAt));}
function nextSlot(base:Date){const d=new Date(base);d.setSeconds(0,0);const m=d.getMinutes();d.setMinutes(m<30?30:60);if(d.getHours()>23 || (d.getHours()===23&&d.getMinutes()>30)){d.setDate(d.getDate()+1);d.setHours(12,0,0,0);}else if(d.getHours()<12){d.setHours(12,0,0,0);}return d;}
export async function saveQueueVideo(file:File,title:string){const token=process.env.BLOB_READ_WRITE_TOKEN;if(!token)throw new Error("BLOB_READ_WRITE_TOKEN tanımlı değil.");const id=Date.now().toString(36)+"-"+Math.random().toString(36).slice(2,8);const blobPath=prefix+id+".mp4";const metaPath=prefix+id+".json";const queued=await listQueue();let slot=nextSlot(new Date());const latest=queued.filter(x=>x.status==="queued").map(x=>new Date(x.scheduledAt)).sort((a,b)=>b.getTime()-a.getTime())[0];if(latest&&latest.getTime()>=slot.getTime()){slot=new Date(latest.getTime()+30*60*1000);if(slot.getHours()>23||(slot.getHours()===23&&slot.getMinutes()>30)){slot.setDate(slot.getDate()+1);slot.setHours(12,0,0,0);}}await put(blobPath,file,{access:"private",addRandomSuffix:false,token});const item:QueueItem={id,filename:file.name,title:title||file.name,status:"queued",scheduledAt:slot.toISOString(),blobPath,createdAt:new Date().toISOString()};await put(metaPath,JSON.stringify(item),{access:"private",addRandomSuffix:false,token});return item;}
export async function downloadQueueVideo(item:QueueItem){const token=process.env.BLOB_READ_WRITE_TOKEN;if(!token)throw new Error("BLOB_READ_WRITE_TOKEN tanımlı değil.");const r=await get(item.blobPath,{access:"private",token});if(!r?.stream)throw new Error("Kuyruk videosu bulunamadı.");const rd=r.stream.getReader();const c:Buffer[]=[];while(true){const x=await rd.read();if(x.done)break;if(x.value)c.push(Buffer.from(x.value));}const p=path.join(os.tmpdir(),item.filename.replace(/[^a-zA-Z0-9._-]/g,"_"));await fs.writeFile(p,Buffer.concat(c));return p;}
export async function updateQueue(item:QueueItem){const token=process.env.BLOB_READ_WRITE_TOKEN;if(token)await put(prefix+item.id+".json",JSON.stringify(item),{access:"private",addRandomSuffix:false,token});return item;}
