"use client";
import {useEffect,useState} from "react";
type Item={title:string;source:string;status:string;updatedAt:string;canvaEditUrl?:string;canvaViewUrl?:string}; type Queue={id:string;filename:string;title:string;status:string;scheduledAt:string;youtubeVideoId?:string};
export default function Page(){const[items,setItems]=useState<Item[]>([]);const[queue,setQueue]=useState<Queue[]>([]);const[loading,setLoading]=useState(false);const[msg,setMsg]=useState("");
async function refresh(){const[a,b]=await Promise.all([fetch("/api/news/status",{cache:"no-store"}),fetch("/api/news/queue/status",{cache:"no-store"})]);const ad=await a.json(),bd=await b.json();setItems(ad.items||[]);setQueue(bd.items||[]);}
async function processNews(){setLoading(true);setMsg("");try{const r=await fetch("/api/news/process",{method:"POST"});const d=await r.json();setMsg(d.error||(d.ok?d.count+" haber için Canva tasarımı oluşturuldu.":"İşlem tamamlanamadı."));await refresh();if("Notification"in window&&Notification.permission==="granted"&&d.count)new Notification("AIO Dijital",{body:d.count+" haber kontrol için Canva'ya hazır."});if("Notification"in window&&Notification.permission==="default")await Notification.requestPermission();}finally{setLoading(false);}}
async function upload(file:File){const form=new FormData();form.append("file",file);const r=await fetch("/api/news/queue/upload",{method:"POST",body:form});const d=await r.json();setMsg(d.error||("Yüklendi: "+new Date(d.item.scheduledAt).toLocaleString("tr-TR")));await refresh();}
useEffect(()=>{refresh();},[]);
return <main style={{maxWidth:1100,margin:"40px auto",padding:20,fontFamily:"Arial,sans-serif"}}><h1>AIO Dijital — Haber Otomasyonu</h1><p>Haber → AI metin → Canva kopyası → senin kontrolün → MP4 yükleme → 30 dk aralıklarla YouTube</p>
<div style={{display:"flex",gap:12,flexWrap:"wrap",margin:"24px 0"}}><button onClick={processNews} disabled={loading}>{loading?"Haberler hazırlanıyor...":"Yeni Haberleri Getir"}</button><button onClick={()=>"Notification"in window&&Notification.requestPermission()}>Bildirimleri Aç</button><label style={{border:"1px solid #ccc",padding:"8px 12px",borderRadius:6,cursor:"pointer"}}>Kontrol ettiğin MP4'ü yükle<input hidden type="file" accept="video/mp4" onChange={e=>e.target.files?.[0]&&upload(e.target.files[0])}/></label></div><p>{msg}</p>
<h2>Kontrol Bekleyen Canva Tasarımları</h2><table style={{width:"100%",borderCollapse:"collapse"}}><thead><tr><th align="left">Haber</th><th align="left">Durum</th><th align="left">Canva</th></tr></thead><tbody>{items.map((x,i)=><tr key={x.title+i}><td>{x.title}</td><td>{x.status}</td><td>{x.canvaEditUrl?<a href={x.canvaEditUrl} target="_blank" rel="noreferrer">Düzenle / kontrol et</a>:"-"}</td></tr>)}</tbody></table>
<h2 style={{marginTop:35}}>Yayın Kuyruğu</h2><table style={{width:"100%",borderCollapse:"collapse"}}><thead><tr><th align="left">Video</th><th align="left">Planlanan</th><th align="left">Durum</th></tr></thead><tbody>{queue.map(x=><tr key={x.id}><td>{x.title||x.filename}</td><td>{new Date(x.scheduledAt).toLocaleString("tr-TR",{timeZone:"Europe/Istanbul"})}</td><td>{x.status}{x.youtubeVideoId?" — "+x.youtubeVideoId:""}</td></tr>)}</tbody></table></main>}
